name: Node Build.

on: [push]

jobs:
    mainbuild:
        runs-on: ${{ matrix.os }}
     
    strategy:
        matrix:
            node-version: [12.x]
            os: [windows-latest]
         
    steps:
      - name: Run a one-line script
        run: echo "Hello World"
